/** 
 * Classes generated by JCasGen based on the type system information defined in 
 *  /com.dalelane.uima.bluemixhelloworld/typeSystemDescriptor.xml
 */
package com.dalelane.uima.bluemixhelloworld.annotations;